version: 0.2
#
env:
  variables:
    DOCKER_USERNAME: "uner4s"
    DOCKER_ACCESS: "dc007a9f-d730-4519-9119-26bce8bdce97"
    DOCKERCONTAINER: "uner4s"
    IMAGE_REPO_NAME: "test-image"
phases:
  install:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7)
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $DOCKERCONTAINER/$IMAGE_REPO_NAME:latest -t $DOCKERCONTAINER/$IMAGE_REPO_NAME:$COMMIT_HASH -f Dockerfile .
      - aws eks --region us-east-1 update-kubeconfig --name main-cluster
  post_build:
    commands:
      - docker login --username $DOCKER_USERNAME --password $DOCKER_ACCESS
      - docker push $DOCKERCONTAINER/$IMAGE_REPO_NAME:latest
      - docker push $DOCKERCONTAINER/$IMAGE_REPO_NAME:$COMMIT_HASH
      - kubectl set image deployment/teledoc-app-deployment --record=true teledoc-app=$IMAGE_REPO_NAME/$DOCKERCONTAINER:$COMMIT_HASH
